// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN1yWf1SB_88WHWcEdBw5_O7HK-UBJwuc',
    appId: '1:977974701135:web:b091aeef16ecb72a780e3a',
    messagingSenderId: '977974701135',
    projectId: 'flowvenue-99a94',
    authDomain: 'flowvenue-99a94.firebaseapp.com',
    storageBucket: 'flowvenue-99a94.firebasestorage.app',
    measurementId: 'G-SLTVGD39Q8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj7okaJ-1eNmoO17KhgVaBHiXURIw5ovA',
    appId: '1:977974701135:android:c6df8ae6ae6ab36a780e3a',
    messagingSenderId: '977974701135',
    projectId: 'flowvenue-99a94',
    storageBucket: 'flowvenue-99a94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkulrJX1tV7b2ff4Vg33hTEH1XkQWbI28',
    appId: '1:977974701135:ios:c6ae0a7d26708922780e3a',
    messagingSenderId: '977974701135',
    projectId: 'flowvenue-99a94',
    storageBucket: 'flowvenue-99a94.firebasestorage.app',
    iosBundleId: 'com.example.flowvenue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkulrJX1tV7b2ff4Vg33hTEH1XkQWbI28',
    appId: '1:977974701135:ios:c6ae0a7d26708922780e3a',
    messagingSenderId: '977974701135',
    projectId: 'flowvenue-99a94',
    storageBucket: 'flowvenue-99a94.firebasestorage.app',
    iosBundleId: 'com.example.flowvenue',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN1yWf1SB_88WHWcEdBw5_O7HK-UBJwuc',
    appId: '1:977974701135:web:1ab5365103d2b7b2780e3a',
    messagingSenderId: '977974701135',
    projectId: 'flowvenue-99a94',
    authDomain: 'flowvenue-99a94.firebaseapp.com',
    storageBucket: 'flowvenue-99a94.firebasestorage.app',
    measurementId: 'G-D04XKJ7V75',
  );

}